Repository GSG-CF05/finance-app-team2, pull requests merged in 2022-02, with the labels that each got.

#3 Creating the file structure
  assets/css/home.css
  assets/css/money.css
  assets/css/normalize.css
  assets/css/style.css
  assets/css/wallet.css
  home.html
  index.html
  money.html
  wallet.html
Labels: approved

#4 Written README file
  README.md
Labels: approved

#11 5 home page structure
  assets/images/CurrencyCrushCoins.svg
  assets/images/HomeIndicator.svg
  assets/images/ProfilePic@2x.svg
  assets/images/Shopping.svg
  assets/images/activity.svg
  assets/images/home.svg
  assets/images/mail-send.svg
  assets/images/options.svg
  assets/images/request.svg
  assets/images/room.svg
  assets/images/shopping-cart-ecommerce.svg
  assets/images/statistics.svg
  assets/images/wallet.svg
  home.html
Labels: approved

#12 replacing some pictures, slightly editing the html structure, and sty…
  assets/css/home.css
  assets/images/Shopping.svg
  assets/images/mail-send.svg
  assets/images/more-icon.svg
  assets/images/options.svg
  assets/images/request-icon.svg
  assets/images/request.svg
  assets/images/room.svg
  assets/images/send-icon.svg
  assets/images/shopping-cart-ecommerce.svg
  home.html
Labels: approved

#9 create on-boarding page and style it.
  assets/css/style.css
  assets/images/img.jpg
  index.html
Labels: awaiting-review

#13 Making the home page responsive - editing the footer and the font size
  assets/css/home.css
Labels: awaiting-review

#16 create the third page and style it.
  assets/css/money.css
  assets/css/wallet.css
  assets/images/acticity.svg
  assets/images/american.svg
  assets/images/arrow.svg
  assets/images/credit.svg
  assets/images/more.svg
  assets/images/paypal.svg
  assets/images/profile.svg
  assets/images/user.svg
  assets/images/visa.svg
  money.html
  wallet.html
Labels: awaiting-review

#20 19 complete readme
  README.md
Labels: done

#18 complete the last page
  assets/css/money.css
  assets/images/arrow.jpg
  assets/images/credit.jpg
  assets/images/currency.jpg
  assets/images/currency.svg
  index.html
  money.html
Labels: approve

#22 21 money page responsive
  assets/css/money.css
Labels: awaiting-review

#24 Finishing the README.md file
  README.md
Labels: awaiting-review

#25 Changing Finance with Financy
  README.md
Labels: awaiting-review
